/*
 * Copyright (C) 2006-2019 Istituto Italiano di Tecnologia (IIT)
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms of the
 * BSD-3-Clause license. See the accompanying LICENSE file for details.
 */

// Autogenerated by Thrift Compiler (0.12.0-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_ACTIONID_H
#define YARP_THRIFT_GENERATOR_STRUCT_ACTIONID_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

namespace yarp {
namespace BT_wrappers {

class ActionID :
        public yarp::os::idl::WirePortable
{
public:
    // Fields
    std::string target;
    std::string resources;
    std::int32_t action_ID;
    std::string BT_filename;

    // Default constructor
    ActionID();

    // Constructor with field values
    ActionID(const std::string& target,
             const std::string& resources,
             const std::int32_t action_ID,
             const std::string& BT_filename);

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<ActionID> unwrapped;

    class Editor :
            public yarp::os::Wire,
            public yarp::os::PortWriter
    {
    public:
        // Editor: default constructor
        Editor();

        // Editor: constructor with base class
        Editor(ActionID& obj);

        // Editor: destructor
        ~Editor() override;

        // Editor: Deleted constructors and operator=
        Editor(const Editor& rhs) = delete;
        Editor(Editor&& rhs) = delete;
        Editor& operator=(const Editor& rhs) = delete;
        Editor& operator=(Editor&& rhs) = delete;

        // Editor: edit
        bool edit(ActionID& obj, bool dirty = true);

        // Editor: validity check
        bool isValid() const;

        // Editor: state
        ActionID& state();

        // Editor: start editing
        void start_editing();

#ifndef YARP_NO_DEPRECATED // Since YARP 3.2
        YARP_DEPRECATED_MSG("Use start_editing() instead")
        void begin()
        {
            start_editing();
        }
#endif // YARP_NO_DEPRECATED

        // Editor: stop editing
        void stop_editing();

#ifndef YARP_NO_DEPRECATED // Since YARP 3.2
        YARP_DEPRECATED_MSG("Use stop_editing() instead")
        void end()
        {
            stop_editing();
        }
#endif // YARP_NO_DEPRECATED

        // Editor: target field
        void set_target(const std::string& target);
        const std::string& get_target() const;
        virtual bool will_set_target();
        virtual bool did_set_target();

        // Editor: resources field
        void set_resources(const std::string& resources);
        const std::string& get_resources() const;
        virtual bool will_set_resources();
        virtual bool did_set_resources();

        // Editor: action_ID field
        void set_action_ID(const std::int32_t action_ID);
        std::int32_t get_action_ID() const;
        virtual bool will_set_action_ID();
        virtual bool did_set_action_ID();

        // Editor: BT_filename field
        void set_BT_filename(const std::string& BT_filename);
        const std::string& get_BT_filename() const;
        virtual bool will_set_BT_filename();
        virtual bool did_set_BT_filename();

        // Editor: clean
        void clean();

        // Editor: read
        bool read(yarp::os::ConnectionReader& connection) override;

        // Editor: write
        bool write(yarp::os::ConnectionWriter& connection) const override;

    private:
        // Editor: state
        ActionID* obj;
        bool obj_owned;
        int group;

        // Editor: dirty variables
        bool is_dirty;
        bool is_dirty_target;
        bool is_dirty_resources;
        bool is_dirty_action_ID;
        bool is_dirty_BT_filename;
        int dirty_count;

        // Editor: send if possible
        void communicate();

        // Editor: mark dirty overall
        void mark_dirty();

        // Editor: mark dirty single fields
        void mark_dirty_target();
        void mark_dirty_resources();
        void mark_dirty_action_ID();
        void mark_dirty_BT_filename();

        // Editor: dirty_flags
        void dirty_flags(bool flag);
    };

private:
    // read/write target field
    bool read_target(yarp::os::idl::WireReader& reader);
    bool write_target(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_target(yarp::os::idl::WireReader& reader);
    bool nested_write_target(const yarp::os::idl::WireWriter& writer) const;

    // read/write resources field
    bool read_resources(yarp::os::idl::WireReader& reader);
    bool write_resources(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_resources(yarp::os::idl::WireReader& reader);
    bool nested_write_resources(const yarp::os::idl::WireWriter& writer) const;

    // read/write action_ID field
    bool read_action_ID(yarp::os::idl::WireReader& reader);
    bool write_action_ID(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_action_ID(yarp::os::idl::WireReader& reader);
    bool nested_write_action_ID(const yarp::os::idl::WireWriter& writer) const;

    // read/write BT_filename field
    bool read_BT_filename(yarp::os::idl::WireReader& reader);
    bool write_BT_filename(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_BT_filename(yarp::os::idl::WireReader& reader);
    bool nested_write_BT_filename(const yarp::os::idl::WireWriter& writer) const;
};

} // namespace yarp
} // namespace BT_wrappers

#endif // YARP_THRIFT_GENERATOR_STRUCT_ACTIONID_H
