/*
 * Copyright (C) 2006-2019 Istituto Italiano di Tecnologia (IIT)
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms of the
 * BSD-3-Clause license. See the accompanying LICENSE file for details.
 */

// Autogenerated by Thrift Compiler (0.12.0-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_BLACKBOARDWRAPPER_H
#define YARP_THRIFT_GENERATOR_SERVICE_BLACKBOARDWRAPPER_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <yarp/os/Property.h>

namespace yarp {
namespace BT_wrappers {

class BlackBoardWrapper :
        public yarp::os::Wire
{
public:
    // Constructor
    BlackBoardWrapper();

    virtual yarp::os::Property getData(const std::string& target);

    virtual bool setData(const std::string& target, const yarp::os::Property& datum);

    virtual void clearData(const std::string& target);

    virtual void clearAll();

    virtual void resetData();

    virtual std::vector<std::string> listTarget();

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

} // namespace yarp
} // namespace BT_wrappers

#endif // YARP_THRIFT_GENERATOR_SERVICE_BLACKBOARDWRAPPER_H
