/*
 * Copyright (C) 2006-2019 Istituto Italiano di Tecnologia (IIT)
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms of the
 * BSD-3-Clause license. See the accompanying LICENSE file for details.
 */

// Autogenerated by Thrift Compiler (0.12.0-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_ENUM_RETURNSTATUS_H
#define YARP_THRIFT_GENERATOR_ENUM_RETURNSTATUS_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

namespace yarp {
namespace BT_wrappers {

/**
 * Enumerates the states every node can be in after execution during a particular
 * time step:
 * - "BT_SUCCESS" indicates that the node has completed running during this time step;
 * - "BT_FAILURE" indicates that the node has determined it will not be able to complete
 *   its task;
 * - "BT_RUNNING" indicates that the node has successfully moved forward during this
 *   time step, but the task is not yet complete;
 * - "BT_IDLE" indicates that the node hasn't run yet.
 * - "BT_HALTED" indicates that the node has been halted by its parent.
 * - "BT_ERROR" indicates the something wrong happened.
 */
enum ReturnStatus
{
    BT_IDLE = 0,
    BT_RUNNING = 1,
    BT_SUCCESS = 2,
    BT_FAILURE = 3,
    BT_HALTED = 4,
    BT_ERROR = 5
};

class ReturnStatusVocab :
        public yarp::os::idl::WireVocab
{
public:
    int fromString(const std::string& input) override;
    std::string toString(int input) const override;
};

} // namespace yarp
} // namespace BT_wrappers

#endif // YARP_THRIFT_GENERATOR_ENUM_RETURNSTATUS_H
