/*
 * Copyright (C) 2006-2019 Istituto Italiano di Tecnologia (IIT)
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms of the
 * BSD-3-Clause license. See the accompanying LICENSE file for details.
 */

// Autogenerated by Thrift Compiler (0.12.0-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_ENUM_RETURNSTATUS_H
#define YARP_THRIFT_GENERATOR_ENUM_RETURNSTATUS_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

namespace yarp {
namespace BT_wrappers {

enum ReturnStatus
{
    BT_IDLE = 0,
    BT_RUNNING = 1,
    BT_SUCCESS = 2,
    BT_FAILURE = 3,
    BT_HALTED = 4,
    BT_ERROR = 5
};

class ReturnStatusVocab :
        public yarp::os::idl::WireVocab
{
public:
    int fromString(const std::string& input) override;
    std::string toString(int input) const override;
};

} // namespace yarp
} // namespace BT_wrappers

#endif // YARP_THRIFT_GENERATOR_ENUM_RETURNSTATUS_H
